#!/bin/bash

export LD_LIBRARY_PATH=..
INTERPRETER=../boron

#DIFF='diff -w --ignore-blank-lines'

case `uname` in
	"CYGWIN"*)
		INTERPRETER=../boron.exe
		DIFF='diff -w'
		;;
	"SunOS") DIFF='diff';;
	*) DIFF='diff -a';;
esac

RC=0
for FILE in $*
do
	echo Test: $FILE
	GOOD=${FILE%.*}.good
	OUT=${FILE%.*}.out
	$INTERPRETER -s $FILE >$OUT
	${DIFF} $OUT $GOOD || RC=1
done
exit $RC
