FIND_PATH(BORONGL_INCLUDE_DIR boron/boron-gl.h /usr/include /usr/local/include)

FIND_LIBRARY(BORONGL_LIBRARY NAMES boron-gl PATH /usr/lib64 /usr/local/lib64 /usr/lib /usr/local/lib) 

IF (BORONGL_INCLUDE_DIR AND BORONGL_LIBRARY)
   SET(BORONGL_FOUND TRUE)
ENDIF (BORONGL_INCLUDE_DIR AND BORONGL_LIBRARY)

IF (BORONGL_FOUND)
   IF (NOT BoronGL_FIND_QUIETLY)
      MESSAGE(STATUS "Found Boron-GL: ${BORONGL_LIBRARY}")
   ENDIF (NOT BoronGL_FIND_QUIETLY)
ELSE (BORONGL_FOUND)
   IF (BoronGL_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find Boron-GL")
   ENDIF (BoronGL_FIND_REQUIRED)
ENDIF (BORONGL_FOUND)
