FIND_PATH(BORON_INCLUDE_DIR boron/urlan.h /usr/include /usr/local/include)

FIND_LIBRARY(BORON_LIBRARY NAMES boron PATH /usr/lib64 /usr/local/lib64 /usr/lib /usr/local/lib) 

IF (BORON_INCLUDE_DIR AND BORON_LIBRARY)
   SET(BORON_FOUND TRUE)
ENDIF (BORON_INCLUDE_DIR AND BORON_LIBRARY)

IF (BORON_FOUND)
   IF (NOT Boron_FIND_QUIETLY)
      MESSAGE(STATUS "Found Boron: ${BORON_LIBRARY}")
   ENDIF (NOT Boron_FIND_QUIETLY)
ELSE (BORON_FOUND)
   IF (Boron_FIND_REQUIRED)
      MESSAGE(FATAL_ERROR "Could not find Boron")
   ENDIF (Boron_FIND_REQUIRED)
ENDIF (BORON_FOUND)
