enum UrlanFixedAtoms
{
    UR_ATOM_QUIT = 64,
    UR_ATOM_HALT,
    UR_ATOM_RETURN,
    UR_ATOM_BREAK,
    UR_ATOM_GHOST,

    UR_ATOM_LATIN1,
    UR_ATOM_UTF8,
    UR_ATOM_UCS2,

    UR_ATOM_PLUS,
    UR_ATOM_MINUS,
    UR_ATOM_SLASH,
    UR_ATOM_ASTERISK,
    UR_ATOM_EQUAL,
    UR_ATOM_LT,
    UR_ATOM_GT,
    UR_ATOM_LTE,
    UR_ATOM_GTE,

    UR_ATOM_X,
    UR_ATOM_Y,
    UR_ATOM_Z,
    UR_ATOM_R,
    UR_ATOM_G,
    UR_ATOM_B,
    UR_ATOM_A,

    UR_ATOM_BAR,
    UR_ATOM_OPT,
    UR_ATOM_SOME,
    UR_ATOM_ANY,
    UR_ATOM_SKIP,
    UR_ATOM_SET,
    UR_ATOM_COPY,
    UR_ATOM_TO,
    UR_ATOM_THRU,
    UR_ATOM_PLACE,

    UR_ATOM_CRC16,
    UR_ATOM_SHA1
};
