#ifndef URLAN_ATOMS_H
#define URLAN_ATOMS_H

enum UrlanFixedAtoms
{
    UR_ATOM_I8 = 64,
    UR_ATOM_U8,
    UR_ATOM_I16,
    UR_ATOM_U16,
    UR_ATOM_I32,
    UR_ATOM_U32,
    UR_ATOM_F32,
    UR_ATOM_F64,
    UR_ATOM_I64,
    UR_ATOM_U64,

    UR_ATOM_NONE,
    UR_ATOM_TRUE,
    UR_ATOM_FALSE,
    UR_ATOM_ON,
    UR_ATOM_OFF,
    UR_ATOM_YES,
    UR_ATOM_NO,

    UR_ATOM_QUIT,
    UR_ATOM_HALT,
    UR_ATOM_RETURN,
    UR_ATOM_BREAK,
    UR_ATOM_CONTINUE,
    UR_ATOM_EXTERN,
    UR_ATOM_LOCAL,
    UR_ATOM_SELF,

    UR_ATOM_LATIN1,
    UR_ATOM_UTF8,
    UR_ATOM_UCS2,
    UR_ATOM_URL,

    UR_ATOM_PLUS,
    UR_ATOM_MINUS,
    UR_ATOM_SLASH,
    UR_ATOM_ASTERISK,
    UR_ATOM_EQUAL,
    UR_ATOM_LT,
    UR_ATOM_GT,
    UR_ATOM_LTE,
    UR_ATOM_GTE,

    UR_ATOM_X,
    UR_ATOM_Y,
    UR_ATOM_Z,
    UR_ATOM_R,
    UR_ATOM_G,
    UR_ATOM_B,
    UR_ATOM_A,

    UR_ATOM_BAR,
    UR_ATOM_OPT,
    UR_ATOM_SOME,
    UR_ATOM_ANY,
    UR_ATOM_SKIP,
    UR_ATOM_SET,
    UR_ATOM_COPY,
    UR_ATOM_TO,
    UR_ATOM_THRU,
    UR_ATOM_INTO,
    UR_ATOM_PLACE,
    UR_ATOM_BITS,

    UR_ATOM_BIG_ENDIAN,
    UR_ATOM_LITTLE_ENDIAN
};

#endif
