  "camera: context [\n"
  "    orient: none\n"
  "    position: none\n"
  "    viewport: 0,0,640,480\n"
  "    fov: 65.0\n"
  "    near: 0.1\n"
  "    far: 10.0\n"
  "]\n"
  "ortho-cam: make camera [\n"
  "    fov: 'ortho\n"
  "    near: -100.0\n"
  "    far: 100.0\n"
  "]\n"
  "gui-style:\n"
  "gui-style-proto: context [\n"
  "    texture:\n"
  "    tex-size:\n"
  "    control-font:\n"
  "    title-font:\n"
  "    edit-font:\n"
  "    list-font:\n"
  "    label:\n"
  "    area:\n"
  "    start-dl:\n"
  "    window-margin:\n"
  "    window:\n"
  "    button-size:\n"
  "    button-up:\n"
  "    button-down:\n"
  "    button-hover:\n"
  "    checkbox-size:\n"
  "    checkbox-up:\n"
  "    checkbox-down:\n"
  "    label-dl:\n"
  "    editor:\n"
  "    editor-active:\n"
  "    editor-cursor:\n"
  "    list-header:\n"
  "    list-item:\n"
  "    list-item-selected:\n"
  "    none\n"
  "]\n"
  "animation: context [\n"
  "    value: none\n"
  "    curve: none\n"
  "    period: 1.0\n"
  "    time: 0.0\n"
  "    behavior: 1\n"
  "]\n"
  "draw-list: func [blk] [make draw-prog! blk]\n"
  "switch environs/os [\n"
  "    Linux [mouse-lb: 0x100 mouse-mb: 0x200 mouse-rb: 0x400]\n"
  "    [mouse-lb: 1 mouse-mb: 3 mouse-rb: 2]\n"
  "]\n"
  "load-shader: func [file] [make shader! load file]\n"
  "load-texture: func [file /mipmap /clamp | spec] [\n"
  "    spec: file: load-png file\n"
  "    if mipmap [spec: [file 'mipmap]]\n"
  "    if clamp [spec: [file 'linear 'clamp]]\n"
  "    make texture! spec\n"
  "]\n"
  "unit-matrix:\n"
  "#[1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 1.0]\n"
  "make-matrix: func [pos] [poke copy unit-matrix 13 pos]\n"
