#define DOP_NOP             0
#define DOP_END             1
#define DOP_CLEAR           2
#define DOP_ENABLE          3
#define DOP_DISABLE         4
#define DOP_CALL            5
#define DOP_SOLID           6
#define DOP_MODEL           7
#define DOP_DECAL           8
#define DOP_IMAGE           9
#define DOP_PARTICLE        10
#define DOP_COLOR           11
#define DOP_COLORS          12
#define DOP_VERTS           13
#define DOP_NORMALS         14
#define DOP_UVS             15
#define DOP_ATTRIB          16
#define DOP_POINTS          17
#define DOP_LINES           18
#define DOP_LINE_STRIP      19
#define DOP_TRIS            20
#define DOP_TRI_STRIP       21
#define DOP_TRI_FAN         22
#define DOP_QUADS           23
#define DOP_QUAD_STRIP      24
#define DOP_TRIS_INST       25
#define DOP_SPHERE          26
#define DOP_BOX             27
#define DOP_QUAD            28
#define DOP_CAMERA          29
#define DOP_LIGHT           30
#define DOP_LIGHTING        31
#define DOP_PUSH            32
#define DOP_POP             33
#define DOP_TRANSLATE       34
#define DOP_ROTATE          35
#define DOP_SCALE           36
#define DOP_FONT            37
#define DOP_TEXT            38
#define DOP_SHADER          39
#define DOP_UNIFORM         40
#define DOP_FRAMEBUFFER     41
#define DOP_FRAMEBUFFER_TEX 42
#define DOP_SHADOW_BEGIN    43
#define DOP_SHADOW_END      44
#define DOP_SAMPLES_QUERY   45
#define DOP_SAMPLES_BEGIN   46
#define DOP_BUFFER          47
#define DOP_BUFFER_INST     48
#define DOP_DEPTH_TEST      49
#define DOP_BLEND           50
#define DOP_CULL            51
#define DOP_COLOR_MASK      52
#define DOP_DEPTH_MASK      53
#define DOP_POINT_SIZE      54
#define DOP_POINT_SPRITE    55
#define DOP_READ_PIXELS     56
#define DOP_COUNT           57
